export const services=[
 ['Wedding Packages','Complete wedding day coverage capturing every ritual, emotion, and celebration with cinematic photography and films.','/packages'],['Pre-Wedding','Romantic and cinematic pre-wedding shoots at beautiful locations, telling your love story before the big day.','/services/pre-wedding'],['Photoshoot','Professional photoshoots for couples, individuals, maternity, baby shoots, and special occasions.','/services/photoshoot'],['Birthday Ceremony','From blowing out candles to heartfelt smiles and family moments, we capture every beautiful memory.','/services/birthday'],['Naming Ceremony','Beautiful coverage of your baby’s naming ceremony with natural, emotional, family-focused photography.','/services/naming'],['Ring Ceremony','An elegant record of your engagement rituals, family moments, and celebration.','/services/ring'],['Janeu Package','Traditional photography that captures sacred rituals, family moments, and memories with care.','/services/janeu'],['Retirement Package','A special farewell package to honor a lifetime of achievements and emotional memories.','/services/retirement']];
export const packages=[
 {slug:'basic',name:'Basic Package',price:'₹50,000',items:['Traditional Photography & Videography','Drone (One Function)','Wedding Teaser Video','Wedding Highlights Video','Video Edited (USB + Box)','Instagram Reels (3x)','Wedding Invitation Video','LED Welcome Stand','Frame (12x18 Inch – 2 Frames)','Album (200 Photos)','Wall Calendar','Photo Mug']},
 {slug:'advance',name:'Advance Package',price:'₹80,000',items:['Traditional Photography','Traditional Videography','Drone (Two Functions)','Cinematic Film / Candid Photography (Optional)','Wedding Teaser Video','Wedding Highlights Video','Video Edited (USB + Box)','Instagram Reels (4x)','Wedding Invitation Video','LED Welcome Standees (2x)','Album (300 Photos) + Online View','Frame (12x18 Inch, 16x24 Inch)','Wall Calendar','Photo Mug']},
 {slug:'premium',name:'Premium Package',price:'₹1,00,000',items:['Traditional Photography','Traditional Videography','Cinematic Wedding Videography','Candid Photography','Drone (Two Functions)','Wedding Teaser','Highlights Video','Video Edited (USB + Box)','Instagram Reels (5x)','Wedding Invitation Video','LED Welcome Standees (4x)','LED Wall (One Day) with Live Telecast','Album (400 Photos) & Online View','Frame (16x24 Inch, 16x24 Inch)','Wall Calendar','Photo Mug (2x)','Cushion (2x)']},
 {slug:'ultra-premium',name:'Ultra Premium Package',price:'₹1,50,000',items:['Both Side Traditional Photography','Both Side Traditional Videography','Drone on Wedding Day','Both Side Cinematic Video','Candid Photography on Wedding Day','Wedding Teaser Video','Wedding Highlights Video','Both Side Video Edited (USB + Box)','Instagram Reels (6x)','Both Side Wedding Invitation Video','LED Welcome Standees (2x)','Both Side Album (300 Photos) + Online View','Both Side Frame (12x18 Inch, 16x24 Inch)','Both Side Wall Calendar','Photo Mug (2x)']}
];
export const fallbackGallery=[['Wedding','/images/wed.jpeg'],['Wedding','/images/wed2.jpeg'],['Wedding','/images/wed3.jpeg'],['Pre-Wedding','/images/pre1.jpeg'],['Pre-Wedding','/images/pre2.jpeg'],['Pre-Wedding','/images/pre3.jpeg'],['Engagement / Ring Ceremony','/images/ring1.jpeg'],['Engagement / Ring Ceremony','/images/ring2.jpeg']];
